# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven, Docker, and ECS

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build jar with Maven using Docker profile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - uses: actions/setup-java@v1
    #   with:
    #     java-version: 11
    # - run: mvn -B package --file pom.xml -Pdocker
    # - run: mkdir staging && cp target/*.jar staging
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: Package
    #     path: staging
    -
      name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: wtvamp
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: wtvamp/virtualstoreweb:beta
        build-args: "PROFILE=docker"
   